# Generated by Django 4.0.3 on 2022-03-19 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 19)),
            preserve_default=False,
        ),
    ]
